server:
  port: 8080
  servlet:
    context-path: /users
spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/db_users_test
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:arrahmankm}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:emailaddress@gmail.com}
    password: ${MAIL_PASSWORD:password}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true 
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_OAUTH_ID:CLIENT_ID}
            clientSecret: ${GOOGLE_OAUTH_SECRET:SECRET_VALUE}
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  codec:
    max-in-memory-size: 20MB
jwt:
  secret:
    key:
      users:
        access_token: IaiYw5wsEs9UNE6Y557it0VyIVaMz9PZmXx8EsqlZFM
        expiration: 6000000
        refresh_token:
          expiration: 86400000
        oauth2_token:
          expiration: 300000
      common: IaiYw5wsEs9UNE6Y557it0VyIVaMz9PZmXx8EsqlZFM
  filter:
    disable:
      request:
        uris: /users/api/v1/auth/**,
              /users/api/v1/public/**,
              /users/api/v1/user-to-admin/**,
              /users/api/v1/user-to-therapist/**
aws:
  region: ap-south-1
  s3:
    buckets:
      therapist: therapists-app-bucket
filter:
  url:
    patterns: /api/v1/user-to-admin/*,
              /api/v1/user-to-therapist/*
